placement:
  managedCluster:
    clusterName: <<CLUSTER_NAME>>-dataproc-cluster
    config:
      softwareConfig:
        properties:
          dataproc:pip.packages: google-auth==1.30.0,google-cloud==0.34.0,google-api-python-client==1.12.8
      gceClusterConfig:
        zoneUri: us-east1-b
        metadata:
          'bigquery-connector-version': '1.2.0'
          'spark-bigquery-connector-version': '0.21.0'
          'enable-cloud-sql-hive-metastore': 'false'
          'additional-cloud-sql-instances': '<<PROJECT_ID>>:us-central1:jobs-metadata=tcp:0.0.0.0:5432'
        serviceAccountScopes:
        - https://www.googleapis.com/auth/bigquery
        - https://www.googleapis.com/auth/cloud.useraccounts.readonly
        - https://www.googleapis.com/auth/devstorage.read_write
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/sqlservice.admin
        - https://www.googleapis.com/auth/cloud-platform
      masterConfig:
        machineTypeUri: n1-standard-4
        numInstances: 1
      workerConfig:
        machineTypeUri: n1-standard-4
        numInstances: 2
      initializationActions:
      - executableFile: gs://goog-dataproc-initialization-actions-us-east1/connectors/connectors.sh
      - executableFile: gs://goog-dataproc-initialization-actions-us-east1/cloud-sql-proxy/cloud-sql-proxy.sh
jobs:
- pysparkJob:
    args:
    - gs://gcs-dataproc-workflow-templates/titanic.csv
    - '2'
    - gs://gcs-dataproc-workflow-templates
    mainPythonFileUri: gs://gcs-dataproc-workflow-templates/pgm-1.py
  stepId: step1
- pysparkJob:
    args:
    - gs://gcs-dataproc-workflow-templates
    - <<PROJECT_ID>>.<<DATASET_ID>>.titanic_survived
    mainPythonFileUri: gs://gcs-dataproc-workflow-templates/pgm-2.py
  prerequisiteStepIds:
  - step1
  stepId: step2
- pysparkJob:
    args:
    - <<PROJECT_ID>>.<<DATASET_ID>>.titanic_survived
    - projects/<<PROJECT_ID>>/locations/us
    - PII
    mainPythonFileUri: gs://gcs-dataproc-workflow-templates/pgm-3.py
    jarFileUris:
    - gs://gcs-dataproc-workflow-templates/postgresql-42.2.23.jar
  prerequisiteStepIds:
  - step2
  stepId: step3
- pysparkJob:
    args:
    - gcs-dataproc-workflow-templates
    - app1_result/
    mainPythonFileUri: gs://gcs-dataproc-workflow-templates/pgm-4.py
  prerequisiteStepIds:
  - step2
  stepId: step4
- pysparkJob:
    args:
    - gcs-dataproc-workflow-templates
    - temp/
    mainPythonFileUri: gs://gcs-dataproc-workflow-templates/pgm-4.py
  prerequisiteStepIds:
  - step2
  stepId: step5